---
- name: Download Visual Studio Code .deb package
  ansible.builtin.get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: /tmp/vscode.deb
    mode: '0644'

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Visual Studio Code .deb package
  ansible.builtin.apt:
    deb: /tmp/vscode.deb
    state: present